default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: credit_simulator_api_development

test:
  <<: *default
  database: credit_simulator_api_test

production:
  primary: &primary_production
    <<: *default
    database: credit_simulator_api_production
  cache:
    <<: *primary_production
    database: credit_simulator_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: credit_simulator_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: credit_simulator_api_production_cable
    migrations_paths: db/cable_migrate
